### ISSUE TITLE
browser zooming (ctrl +) can break the reader

### ISSUE THREAD

**Issue by samuelhackwill** [samuelhackwill/le-tiret-du-six#16]
we are going to encourage people to zoom in or zoom out in order to be able to read comfortably. Some people will predictably zoom in a lot (elderly people for instance), which breaks this line of code :  

```css
/* imports/ui/components/reader.css */
ul:last-child{

	color:white;
	margin-bottom:300px;

}
```

we need to make it responsive to the possible zooming in or zooming out of the browser.

![Capture d’écran 2021-04-26 à 16 20 11](https://user-images.githubusercontent.com/6910260/116098682-8ec7a880-a6ab-11eb-9370-3e9b89a4c2e9.png)
at 100% zoom

![Capture d’écran 2021-04-26 à 16 22 45](https://user-images.githubusercontent.com/6910260/116098940-c20a3780-a6ab-11eb-8903-d41b038342ac.png)
at 200% zoom
